<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Google JS tests" failures="11" time="0.01">
 <testcase name="MocksTest.SatisfiedMocks" time="0.01"/>
 <testcase name="MocksTest.MockActions" time="0.01"/>
 <testcase name="MocksTest.MockInstance" time="0.01"/>
 <testcase name="MocksTest.UnexpectedFunctionCall_Simple" time="0.01">
  <failure><![CDATA[mocks_test.js:71: Call matches no expectation.
    Arg 0: 19

Tried expectation at mocks_test.js:68, but arg 0 didn't match:
    Arg 0: 23

Tried expectation at mocks_test.js:67, but arg 0 didn't match:
    Arg 0: 17

Stack:
    mocks_test.js:71
    register.js:176
    run_test.js:37

mocks_test.js:74: Call to bar matches no expectation.
    Arg 0: 29

Stack:
    mocks_test.js:74
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.UnexpectedFunctionCall_RecursivelyEquals" time="0.01">
  <failure><![CDATA[mocks_test.js:85: Call matches no expectation.
    Arg 0: 0

Tried expectation at mocks_test.js:81, but arg 0 (which is not an Array) didn't match:
    Arg 0: recursively equals [ 17, 23 ]

Stack:
    mocks_test.js:85
    register.js:176
    run_test.js:37

mocks_test.js:88: Call to bar matches no expectation.
    Arg 0: 0

Tried expectation at mocks_test.js:82, but arg 0 (which is not an Array) didn't match:
    Arg 0: recursively equals [ 17, 23 ]

Stack:
    mocks_test.js:88
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.UnexpectedMethodCall" time="0.01">
  <failure><![CDATA[mocks_test.js:96: Call to MyClass.doSomething matches no expectation.
    Arg 0: 17

Stack:
    mocks_test.js:96
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.UnsatisfiedExpectations" time="0.01">
  <failure><![CDATA[Unsatisfied expectation at mocks_test.js:105:
    Arg 0: 19

Expected 1 call; called 0 times.

Unsatisfied expectation at mocks_test.js:108:
    Arg 0: 23

Expected 2 calls; called 1 time.

Unsatisfied expectation at mocks_test.js:113:
    Arg 0: 29

Expected 3 calls; called 4 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.AnotherTest" time="0.01"/>
 <testcase name="MocksTest.UnsatisfiedExpectationsWithReferences" time="0.01">
  <failure><![CDATA[Unsatisfied expectation at mocks_test.js:144:
    Arg 0: is a reference to: { name: 'obj_1' }

Expected 1 call; called 0 times.

Unsatisfied expectation at mocks_test.js:147:
    Arg 0: is a reference to: { name: 'obj_2' }

Expected 2 calls; called 1 time.

Unsatisfied expectation at mocks_test.js:152:
    Arg 0: is a reference to: { name: 'obj_3' }

Expected 3 calls; called 4 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.PrecedingExpectThat" time="0.01">
  <failure><![CDATA[mocks_test.js:172: Call matches no expectation.
    Arg 0: 23

Tried expectation at mocks_test.js:170, but arg 0 didn't match:
    Arg 0: 19

Stack:
    mocks_test.js:172
    register.js:176
    run_test.js:37

Unsatisfied expectation at mocks_test.js:170:
    Arg 0: 19

Expected 1 call; called 0 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.ExpectCallWithNonMockFunction" time="0.01">
  <failure><![CDATA[TypeError: Supplied function is not a mock.
        at mocks_test.js:176]]></failure>
 </testcase>
 <testcase name="MocksTest.MissingArguments" time="0.01">
  <failure><![CDATA[mocks_test.js:190: Call matches no expectation.
    (No arguments.)

Tried expectation at mocks_test.js:183, but number of arguments didn't match:
    Arg 0: is anything

Stack:
    mocks_test.js:190
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.TooManyArguments" time="0.01">
  <failure><![CDATA[mocks_test.js:204: Call matches no expectation.
    Arg 0: undefined
    Arg 1: 17

Tried expectation at mocks_test.js:197, but number of arguments didn't match:
    Arg 0: is anything

Stack:
    mocks_test.js:204
    register.js:176
    run_test.js:37

mocks_test.js:205: Call matches no expectation.
    Arg 0: undefined
    Arg 1: undefined

Tried expectation at mocks_test.js:197, but number of arguments didn't match:
    Arg 0: is anything

Stack:
    mocks_test.js:205
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.OptionalArgument" time="0.01"/>
 <testcase name="MocksTest.OptionalOrExactValueArgument" time="0.01">
  <failure><![CDATA[mocks_test.js:233: Call matches no expectation.
    Arg 0: undefined
    Arg 1: undefined

Tried expectation at mocks_test.js:225, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present, or 23

Stack:
    mocks_test.js:233
    register.js:176
    run_test.js:37

mocks_test.js:234: Call matches no expectation.
    Arg 0: undefined
    Arg 1: 24

Tried expectation at mocks_test.js:225, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present, or 23

Stack:
    mocks_test.js:234
    register.js:176
    run_test.js:37

mocks_test.js:235: Call matches no expectation.
    Arg 0: undefined
    Arg 1: 'taco'

Tried expectation at mocks_test.js:225, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present, or 23

Stack:
    mocks_test.js:235
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
 <testcase name="MocksTest.SentinelMatcher" time="0.01">
  <failure><![CDATA[mocks_test.js:250: Call matches no expectation.
    (No arguments.)

Tried expectation at mocks_test.js:243, but number of arguments didn't match:
    Arg 0: is the missing arg sentinel

Stack:
    mocks_test.js:250
    register.js:176
    run_test.js:37]]></failure>
 </testcase>
</testsuite>
